In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
#Numpy array
np.array([1,2,4,5,3],dtype='float32')

array([1., 2., 4., 5., 3.], dtype=float32)

In [4]:
a1=np.array([1,2,4,5,3],dtype='float32')
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [6]:
a2.shape

(2, 3)

In [7]:
a2.ndim

2

In [8]:
a2.dtype

dtype('int64')

In [9]:
a2.size

6

# Creating Numpy Arrays from Scratch

## zeros,ones,full,arange,linspace

In [10]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones([3,5],dtype ='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [15]:
# seed
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [16]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [17]:
np.random.randint(0,10, (4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]], dtype=int32)

# Array indexing & Slicing

In [18]:
x1=np.random.randint(20,size =6)
x1

array([ 6, 11, 14, 18,  0, 14], dtype=int32)

In [19]:
x1[4],x1[0],x1[-1]

(np.int32(0), np.int32(6), np.int32(14))

In [20]:
x2 = np.random.randint(10,size = (3,4))

In [21]:
x2

array([[3, 5, 9, 4],
       [4, 6, 4, 4],
       [3, 4, 4, 8]], dtype=int32)

In [22]:
x2[1,2] = 6

In [23]:
x2

array([[3, 5, 9, 4],
       [4, 6, 6, 4],
       [3, 4, 4, 8]], dtype=int32)

## slicing

In [24]:
#x[start:end:step]

In [25]:
x1

array([ 6, 11, 14, 18,  0, 14], dtype=int32)

In [26]:
x1[0:3]

array([ 6, 11, 14], dtype=int32)

In [27]:
x1[::2]

array([ 6, 14,  0], dtype=int32)

In [28]:
x2

array([[3, 5, 9, 4],
       [4, 6, 6, 4],
       [3, 4, 4, 8]], dtype=int32)

In [29]:
x2[:2,:3]

array([[3, 5, 9],
       [4, 6, 6]], dtype=int32)

In [30]:
x2[:,:2]

array([[3, 5],
       [4, 6],
       [3, 4]], dtype=int32)

## Reshaping of Arrys and Transpose

In [31]:
grid=np.arange(1,10)
grid.shape

(9,)

In [32]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
x=np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [34]:
x.T

array([[1., 3.],
       [2., 4.]])

## Array Concatenation and Splitting

In [35]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [36]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [37]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate((grid,grid)) #mặc định axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate((grid,grid),axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

In [41]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [42]:
y = np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Splitting of arrays

In [43]:
x=np.array([1,2,3,99,56,3,2,1])

In [44]:
x1,x2,x3 =np.split(x,[3,5])

In [45]:
x1

array([1, 2, 3])

In [46]:
x2

array([99, 56])

In [47]:
x3

array([3, 2, 1])

## Broadcasting and Vectorized operations

In [48]:
a = np.arange(3)

In [49]:
a

array([0, 1, 2])

In [50]:
a+5


array([5, 6, 7])

In [51]:
b= np.ones((3,3))

In [52]:
a.shape,b.shape

((3,), (3, 3))

In [53]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [54]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [55]:
c= np.arange(3).reshape((3,1))

In [56]:
c

array([[0],
       [1],
       [2]])

In [57]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays

### Aggregation
Aggregation = performkng the same operation on a number of things

In [58]:
List_number = [1,2,3]

In [59]:
ll= np.array(List_number)
ll

array([1, 2, 3])

In [60]:
sum(ll) # python sum

np.int64(6)

In [61]:
np.sum(ll) # Numpy sum

np.int64(6)

In [62]:
massive_array = np.random.random(10000)
massive_array [:5]
massive_array.shape

(10000,)

In [63]:
%timeit sum(massive_array) # pthon sum
%timeit np.sum(massive_array) # Numpy


529 μs ± 8.79 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.15 μs ± 73.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [64]:
np.mean(massive_array)

np.float64(0.5013998768433062)

In [65]:
np.max(massive_array)

np.float64(0.9999709462497284)

In [66]:
np.min(massive_array)

np.float64(2.0027530115096503e-05)

# Statistics

## Table of contents
Standard Deviation & Variance
### Standard Deviation
Standard Deviation is a measure of how spread out numbers are.    

In [68]:
# Standard deviation a measure of how spread out a group of numbers is from the mean
np.std(a2)
# Standar deviation Square Root of Variance
np.sqrt(np.var(a2))

np.float64(1.707825127659933)

In [69]:
# Variance
# Varainace measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

np.float64(2.9166666666666665)